name: Publish package to GitHub Packages
on:
  release:
    types: [created]
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '20.18.1'
          cache: 'npm'

      - name: Setup .npmrc file
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "@flooz-link:registry=https://npm.pkg.github.com" >> .npmrc
      
      - run: npm install
      - run: npm run lint

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      
      - name: Setup .npmrc file
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "@flooz-link:registry=https://npm.pkg.github.com" >> .npmrc
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build

      - run: npm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}